### PR TITLE
Added more content to SCSS @extend vs @mixin section

### PR DESCRIPTION
**Pull request by eriku**
Added more to @extend vs @mixin section as well as added some spacing under the code blocks

### CODE REVIEW

**Comment by reubenmoes** [comment]
Looks good to me.  The clarity around @extend vs @mixin is good.

**Comment by nathansh** [comment]
Looks good!

**Comment by andmiriam** [comment]
Nice work!

**Comment by reubenmoes** [comment]
@eriku  @lancejanocha @andmiriam @verticalgrain @nathanshubert 
I think we should update this pull request to actually only include the placeholder format.  I have noticed that using `@extend .module` format can lead to some accidental nastiness.  This real example (I was doing it on Earls) ended up causing 10KB of junk

```
.icon {
    font-family: 'icomoon';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    /* Better Font Rendering =========== */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

.social-nav {
    .facebook {
      @extend .icon;
        color: blue;
    }
}

.footer-nav {
  .icon {
      color: orange;
    }
}
```

Compiles to

```
.icon, 
.social-nav .facebook {
  font-family: 'icomoon';
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.social-nav .facebook {
  color: blue;
}

.footer-nav .icon, 
.footer-nav .social-nav .facebook, 
.social-nav .footer-nav .facebook {
  color: orange;
}
```

The issue is that, if you don't use the placeholder (`@extend %icon`) format, then the extend will happen anywhere `.icon` is defined. 

A better approach: 

```
.icon,
%icon{
    font-family: 'icomoon';
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    /* Better Font Rendering =========== */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}

.social-nav {
    .facebook {
      @extend %icon;
        color: blue;
    }
}

.footer-nav {
  .icon {
      color: orange;
    }
}
```

**Comment by eriku** [comment]
I agree. I wrote this before you came across that last week. I removed the .class example all together.

**Comment by reubenmoes** [comment]
Nice.  I think we're good to merge this.  Everybody +1? 
@eriku @lancejanocha @andmiriam @verticalgrain @nathanshubert

**Comment by lancejanocha** [comment]
looks good

**Comment by nathansh** [comment]
Yup

**Comment by andmiriam** [comment]
+1

**Pull request merged**
