### PR TITLE
add url helpers notes

### PR DESCRIPTION
**Pull request by reubenmoes**
Would love to get some opinions on this

### CODE REVIEW

**Comment by verticalgrain** [comment]
Awesome idea, we should use this on all projects going forwards.

**Comment by eriku** [comment]
Love it!

**Comment by andmiriam** [comment]
Makes perfect sense. Let's do it.

**Comment by reubenmoes** [comment]
@eriku  I agree.  relative_assets is already set to true in sassyplate and the config option is related to helper functions so I don't think it would hurt to include it here.  added.

**Comment by eriku** [comment]
I think we're good to merge :)

**Comment by reubenmoes** [comment]
@lancejanocha @nathanshubert  Please review whenever you have a chance.

**Comment by lancejanocha** [comment]
Looks good to me - just ran threw my current project and implemented 'fonts_dir'... worked great

**Pull request merged**
